sudo: required
services:
  - docker

before_install:
  - docker build -t mphbo777/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mphbo777/react-test npm test -- --coverage

after_success:
  - docker build -t mphbo777/complex-client ./client
  - docker build -t mphbo777/complex-nginx ./nginx
  - docker build -t mphbo777/complex-server ./server
  - docker build -t mphbo777/complex-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mphbo777/complex-client
  - docker push mphbo777/complex-nginx
  - docker push mphbo777/complex-server
  - docker push mphbo777/complex-worker